### ISSUE TITLE
Viewer instructions?

### ISSUE THREAD

**Issue by redstreet** [fdd4s/matterport-downloader#1]
Thank you for sharing this script! I'm wondering if there are instructions to view the downloaded matterport in a way similar to the matterport viewer? I see the Panini or three.js links, but neither seems to have instructions to work out of the box with the files downloaded via your script.

A separate question: how is viewing them via one of the above different from using [matterport-dl](https://github.com/rebane2001/matterport-dl) (which sadly isn't maintained any more)? I did notice that your script downloads far less than matterport-dl, and was wondering why that might be so?

Thanks much again!

**Comment by fdd4s** [comment]
This script only downloads panos 360 photos, matterport (and matterport-dl) has more data like 3d dollhouse view, measure tools and so on.

If you have problems with those viewers, you can try with Pannellum https://github.com/mpetroff/pannellum (it supports skybox and equirectangular 360 images).

But keep in mind: it's just to view the panoramic 360 pics, matterport have more options that this script doesnt use.

This script downloads each panorama in skybox cubemap format (6 pics per panorama). If you want to use something more easy you can try https://github.com/fdd4s/matterport-dl-equi and use the Ricoh Theta viewer (just one file equirectangular per pano).

**Comment by redstreet** [comment]
Thanks much for the explanation and the pointers, that makes sense. I'll check out Pannellum.

**Comment by redstreet** [comment]
Pannellum was simple to use and works great for matterport.

For anyone else needing this: the ordering of matterport skybox files that's needed for Pannellum is: `1 2 3 4 0 5`

Thanks again!
